// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-bio.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var BIO = {
  name: "Mohamed Mahmoud Seliem",
  headline: "Physical Therapist \u2192 Data Analyst",
  tagline: "Turning Chaos into Clarity",
  location: "Dakahlia, Egypt",
  email: "muhammadsleem03@gmail.com",
  linkedin: "https://linkedin.com/in/sleemisme",
  github: "https://github.com/Sleem13",
  languages: ["Arabic (Native)", "English (Fluent)", "French (Basic)"],
  summary: "Licensed Physical Therapist turned Data Analyst with 5+ years of clinical leadership experience. Combines frontline clinical empathy with analytical rigor to build data and AI solutions in healthcare."
};
var get_bio_default = defineTool({
  name: "get_bio",
  title: "Get bio",
  description: "Returns Mohamed Seliem's short bio, tagline, location, and public contact links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(BIO, null, 2) }],
    structuredContent: BIO
  })
});

// src/lib/mcp/tools/list-experience.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
var EXPERIENCE = [
  {
    role: "Data Analyst",
    company: "Digilians, MTC & MCIT",
    period: "Nov 2025 \u2013 Present",
    highlights: [
      "Python & SQL automation pipelines",
      "Predictive ML models",
      "Power BI dashboards",
      "15% efficiency gain, 22% faster recovery identification"
    ]
  },
  {
    role: "Senior Physical Therapist",
    company: "Ministry of Health & Population",
    period: "Sep 2020 \u2013 Present",
    highlights: [
      "300+ patient cases per year",
      "95%+ satisfaction rate",
      "Mentored junior therapists on evidence-based methodologies"
    ]
  },
  {
    role: "Sports Rehabilitation Specialist",
    company: "N.E.C",
    period: "Sep 2021 \u2013 Apr 2023",
    highlights: ["Phased recovery programs with performance benchmarking"]
  },
  {
    role: "Pediatric Habilitation Therapist",
    company: "Nour Elhayat Oasis",
    period: "May 2020 \u2013 Mar 2021",
    highlights: ["Established measurable developmental KPIs"]
  }
];
var list_experience_default = defineTool2({
  name: "list_experience",
  title: "List experience",
  description: "Returns Mohamed Seliem's career experience timeline.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(EXPERIENCE, null, 2) }],
    structuredContent: { experience: EXPERIENCE }
  })
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
var PROJECTS = [
  {
    name: "RehabRL",
    description: "Deep reinforcement learning agent for adaptive physical therapy protocols.",
    repo: "https://github.com/Sleem13/rehab_rl",
    stack: ["Python", "PyTorch", "Reinforcement Learning"]
  },
  {
    name: "Patient Outcome Prediction Engine",
    description: "Supervised ML pipeline that flags at-risk patients earlier from clinical notes and vitals.",
    stack: ["scikit-learn", "Pandas", "Python"],
    impact: {
      "faster recovery identification": "22%",
      "misdiagnosis reduction": "18%"
    }
  },
  {
    name: "Healthcare Operations Dashboard",
    description: "Automated ETL + Power BI dashboards consolidating 5+ sources of clinic operations data.",
    stack: ["Power BI", "SQL", "Python", "DAX"],
    impact: {
      "efficiency gain": "15%",
      "hours saved per week": "20+"
    }
  },
  {
    name: "Rehabilitation Progress Tracker",
    description: "Standardized clinical KPIs across a therapist team to accelerate plan adjustments.",
    stack: ["Python", "Pandas"],
    impact: {
      "patient satisfaction": "95%+",
      "faster plan adjustments": "30%"
    }
  }
];
var list_projects_default = defineTool3({
  name: "list_projects",
  title: "List projects",
  description: "Returns Mohamed Seliem's featured case studies and repos with impact metrics.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(PROJECTS, null, 2) }],
    structuredContent: { projects: PROJECTS }
  })
});

// src/lib/mcp/tools/list-skills.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
var SKILLS = {
  technical: [
    "Python",
    "SQL",
    "Power BI",
    "Tableau",
    "scikit-learn",
    "Pandas",
    "ETL Pipelines",
    "DAX",
    "Statistical Modeling",
    "Machine Learning",
    "Automation"
  ],
  clinical: [
    "Clinical Assessment & Triage",
    "Musculoskeletal Rehabilitation",
    "Neuromuscular Therapy",
    "Sports Injury Recovery",
    "Dry Needling & Acupuncture",
    "Pediatric Habilitation"
  ],
  certifications: [
    "Google Data Analytics Professional Certificate",
    "Agile & Lean Methodologies",
    "Applied AI & Healthcare Data Integration"
  ]
};
var list_skills_default = defineTool4({
  name: "list_skills",
  title: "List skills",
  description: "Returns Mohamed Seliem's technical stack, clinical expertise, and certifications.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(SKILLS, null, 2) }],
    structuredContent: SKILLS
  })
});

// src/lib/mcp/index.ts
var projectRef = "qosnlahyxykfxkkezugq";
var mcp_default = defineMcp({
  name: "seliem-portfolio-mcp",
  title: "Seliem Portfolio",
  version: "0.1.0",
  instructions: "Tools for Mohamed Mahmoud Seliem's portfolio. Use these to answer questions about his bio, experience, featured projects, and skills.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_bio_default, list_experience_default, list_projects_default, list_skills_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
